import { getLayout } from "../js/utils";

export const pageStyles = {
  pageContainer: {
    paddingBottom: "100px",
    overflowY: "auto",
  },
  stickyCard: {
    position: "sticky",
    top: "0",
    zIndex: "100",
    margin: "15px",
    borderRadius: "12px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  },
  quickNav: {
    position: "sticky",
    top: "0",
    zIndex: "10",
    backgroundColor: "var(--f7-bars-bg-color)",
    padding: "10px",
    borderBottom: "1px solid var(--f7-bars-border-color)",
  },
  maquetteNumber: {
    position: "sticky",
    zIndex: "100",
    margin: "15px",
  },
  maquetteCard: {
    margin: "15px",
    borderRadius: "12px",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  maquetteImage: {
    width: "100%",
    maxWidth: "380px",
    height: "auto",
    margin: "15px auto",
    display: "block",
    borderRadius: "12px",
    boxShadow: "0 4px 16px rgba(0,0,0,0.15)",
    transition: "transform 0.2s",
  },
  maquetteTitle: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    fontSize: "1.3em",
    fontWeight: "600",
    color: "var(--f7-text-color)",
    marginBottom: "15px",
  },
  sectionHeader: {
    background: "linear-gradient(135deg, var(--app-primary-color), #0051d5)",
    color: "white",
    padding: "15px",
    borderRadius: "12px 12px 0 0",
    fontSize: "1.1em",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  goldenRuleCard: {
    background: "linear-gradient(135deg, #fff3cd, #ffeaa7)",
    border: "none",
    borderRadius: "15px",
    margin: "15px",
    boxShadow: "0 6px 20px rgba(253, 203, 110, 0.3)",
  },
  goldenRuleHeader: {
    background: "linear-gradient(135deg, #fdcb6e, #e17055)",
    color: "white",
    fontSize: "1.2em",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  introText: {
    fontSize: "1.1em",
    lineHeight: "1.6",
    marginBottom: "15px",
    color: "#856404",
  },
  imageDisplayContainer: {
    padding: "20px",
    backgroundColor: "var(--f7-card-bg-color)",
    marginBottom: "20px",
    borderRadius: "12px",
    position: "relative",
  },
  difficultyBadge: {
    position: "absolute",
    top: "15px",
    right: "15px",
    zIndex: "5",
  },
  imageDisplayText: {
    fontSize: "1em",
    lineHeight: "1.6",
    marginTop: "15px",
    textAlign: "left",
    maxWidth: "400px",
    margin: "15px auto 0",
    color: "var(--f7-text-color)",
  },
  imageDisplayNotes: {
    fontSize: "0.95em",
    lineHeight: "1.5",
    marginTop: "15px",
    textAlign: "left",
    margin: "15px auto 0",
    fontStyle: "italic",
    // color: "var(--f7-color-gray)",
    backgroundColor: getLayout()?.colorScheme?.[2],
    padding: "12px",
    borderRadius: "8px",
    borderLeft: "4px solid var(--f7-color-blue)",
  },
  quizContainer: {
    marginTop: "20px",
    padding: "15px",
    backgroundColor: "var(--f7-block-bg-color)",
    borderRadius: "12px",
    border: "1px solid var(--f7-bars-border-color)",
  },
  answerInput: {
    width: "100%",
    padding: "15px",
    fontSize: "1em",
    border: "2px solid var(--f7-input-border-color)",
    borderRadius: "10px",
    outline: "none",
    transition: "border-color 0.3s, box-shadow 0.3s",
    backgroundColor: "var(--f7-input-bg-color)",
    color: "var(--f7-input-text-color)",
  },
  answerSection: {
    backgroundColor: "var(--f7-color-blue-tint-9)",
    border: "2px solid var(--f7-color-blue)",
    borderRadius: "10px",
    padding: "15px",
    margin: "15px 0",
    color: "var(--f7-color-blue-shade-2)",
    fontSize: "1.1em",
    fontWeight: "500",
  },
  userAnswerDisplay: {
    marginTop: "10px",
    padding: "8px 12px",
    backgroundColor: "var(--f7-color-gray-tint-9)",
    borderRadius: "6px",
    fontSize: "0.9em",
    fontStyle: "italic",
  },
  backToTopFab: {
    position: "fixed",
    bottom: "80px",
    right: "20px",
    zIndex: "100",
  },
  progressIndicator: {
    position: "sticky",
    top: "60px",
    zIndex: "9",
    padding: "0 15px 10px",
    backgroundColor: "var(--f7-bars-bg-color)",
  },
};