export const auto_bedrijven_paramaribo = {
  auto_bedrijven_paramaribo: {
    laatste_update: "2025-08-17",
    locatie: "Paramaribo, Suriname",
    categorieën: {
      autoreparatiebedrijven: [
        {
          naam: "Artko Trading N.V.",
          adres: "Indira Gandhiweg 995 & Ds. M.L. Kingweg 16",
          telefoon: "+597 480285 (garage), +597 480534 (winkel)",
          whatsapp: "+597 8588725",
          diensten: [
            "Airconditioning onderhoud en reparatie",
            "Motor reparatie",
            "Transmissie reparatie",
            "Remsysteem reparatie",
            "Onderstel reparatie",
            "Schokbreker vervanging",
            "Algemene reparaties",
          ],
          specialiteiten: "Officiële leverancier MASUMA auto-onderdelen",
          openingstijden: "Ma-Vr: 8:00-17:00, Za: 8:00-14:00",
          beschrijving:
            "Vooraanstaand autoreparatiebedrijf met twee vestigingen en focus op klanttevredenheid",
        },
        {
          naam: "Kyoto Car Service & Parts",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via Facebook",
          diensten: [
            "Auto service & reparatie",
            "Auto-onderdelen verkoop",
            "Banden verkoop",
            "Smeermiddelen",
            "Auto-accessoires",
          ],
          specialiteiten:
            "Gegarandeerd het goedkoopste service & reparatie bedrijf van Suriname",
          beschrijving:
            "Service en reparatiebedrijf met uitgebreid assortiment auto-onderdelen",
        },
        {
          naam: "Toyota Service & Repair Center",
          adres: "Ringweg-Zuid (Ring Center Plaza complex)",
          telefoon: "Beschikbaar via website",
          diensten: [
            "Toyota service en reparatie",
            "Originele Toyota onderdelen",
            "Toyota olieën en filters",
          ],
          specialiteiten: "Toyota Certified service center",
          beschrijving:
            "Officieel Toyota service center met originele onderdelen",
        },
        {
          naam: "Fernandes Autohandel - Service",
          adres: "Keizerstraat 105-117 & Jaggernath Lachmonstraat 126",
          telefoon: "+597 475046",
          whatsapp: "+597 8427943 (Service & reparatie)",
          diensten: [
            "Autoreparatie",
            "Onderhoud",
            "Night shift service (16:00-00:30)",
            "Isuzu truck service",
          ],
          openingstijden: "Ma-Vr: 8:00-16:30, Za: 9:00-13:00",
          beschrijving:
            "Gevestigde autohandel met uitgebreide service faciliteiten",
        },
        {
          naam: "Garage de Paarl",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via website",
          diensten: [
            "Autoreparatie",
            "Airport transport",
            "Limousine service",
            "Auto verhuur",
          ],
          specialiteiten: "The only real reliable garage in Suriname",
          beschrijving: "Betrouwbare garage met transport en verhuur diensten",
        },
        {
          naam: "Surin Transmission",
          adres: "Cornelia straat",
          telefoon: "+597 876-9956",
          email: "RTRIX_RRR@HOTMAIL.COM",
          website: "srtransmission.sr",
          diensten: ["Transmissie reparatie", "Versnellingsbak reparatie"],
          specialiteiten: "Gespecialiseerd in transmissie problemen",
          beschrijving: "Specialist in alle soorten transmissie reparaties",
        },
      ],
      auto_onderdelen_winkels: [
        {
          naam: "Artko Trading N.V.",
          adres: "Indira Gandhiweg 995 & Ds. M.L. Kingweg 16",
          telefoon: "+597 480534",
          whatsapp: "+597 8588725",
          producten: [
            "MASUMA auto-onderdelen",
            "Remsysteem onderdelen",
            "Chassisophangingssysteem",
            "Motorsysteem onderdelen",
            "Olieonderhoud producten",
          ],
          specialiteiten:
            "Enige importeur van MASUMA auto-onderdelen in Suriname",
          beschrijving:
            "Uitgebreide collectie van 20.000+ artikelen, 80% uit voorraad leverbaar",
        },
        {
          naam: "ONE Autoparts",
          adres: "Kwattaweg 382",
          telefoon: "+597 433-967",
          whatsapp: "+597 828-1777",
          diensten: [
            "Auto-onderdelen verkoop",
            "Reparatie services",
            "Keuring",
          ],
          beschrijving:
            "Auto-onderdelen winkel met reparatie en keuring diensten",
        },
        {
          naam: "Auto Parts Finder",
          adres: "Kwattaweg",
          diensten: ["Auto-onderdelen verkoop"],
          beschrijving: "Auto-onderdelen winkel gelegen aan de Kwattaweg",
        },
        {
          naam: "Ming Kee Auto Parts",
          adres: "Tourtonnelaan 122-124",
          specialiteiten:
            "Japanse auto onderdelen voor Toyota, Nissan, Honda, Isuzu, Mitsubishi, Mazda, Hyundai, Suzuki",
          beschrijving:
            "Specialist in Japanse auto onderdelen tegen de beste prijzen",
        },
      ],
      auto_accessoires_winkels: [
        {
          naam: "Kirpalani's N.V. - Auto Accessoires",
          adres: "Multiple locations in Paramaribo",
          telefoon: "Beschikbaar via website",
          producten: [
            "Auto radio's",
            "Auto matten",
            "Schoonmaakproducten",
            "Goodyear producten",
            "Pioneer audio systemen",
            "Booster kabels",
            "Auto covers",
          ],
          merken: ["Goodyear", "Pioneer", "Astonish", "Awesome"],
          beschrijving:
            "Uitgebreide collectie auto-accessoires van populaire merken",
        },
        {
          naam: "X-Turbo Auto Accessories & Repair",
          adres: "Herman D. Benjaminstraat 67",
          telefoon: "Beschikbaar via Facebook",
          producten: [
            "Car audio systemen",
            "Velgen",
            "Auto-accessoires",
            "Auto alarm systemen",
            "Raamfolie",
            "Banden",
            "Reservewiel covers",
          ],
          diensten: ["Installatie", "Reparatie"],
          beschrijving:
            "Complete auto-accessoires winkel met installatie services",
        },
        {
          naam: "Auto Style N.V.",
          adres: "Verlengde Gemenelandsweg 117",
          telefoon: "+597 497-689",
          email: "sur.autostyle@gmail.com",
          website: "autostylenv.com",
          producten: [
            "Auto accu's",
            "Auto-onderdelen",
            "Off-road accessoires",
            "Facelift onderdelen",
            "Alarm & sound installatie",
            "Velgen",
          ],
          diensten: ["Onderstel reparatie", "Airco reparatie/service"],
          beschrijving: "Complete auto styling en accessoires winkel",
        },
        {
          naam: "Fernandes Autohandel - Parts",
          adres: "Keizerstraat 105-117",
          whatsapp: "+597 8919554 (Sales & Parts)",
          producten: [
            "Isuzu accessoires",
            "Honda accessoires",
            "Subaru accessoires",
            "Volkswagen Commercial Vehicles accessoires",
            "Carryboy accessoires",
            "Retrax accessoires",
          ],
          beschrijving: "Dealer accessoires voor verschillende automerken",
        },
      ],
      bandenwinkels: [
        {
          naam: "Traverco Truck & Tire Service N.V.",
          adres: "Noordelijke Industrieweg #21",
          telefoon: "Beschikbaar via website",
          website: "travercotire.com",
          specialiteiten: "Suriname's leidende bandenzaak",
          producten: ["Truck banden", "Auto banden", "Banden accessoires"],
          beschrijving:
            "The Best place for all your tires and tire accessories in Suriname",
        },
        {
          naam: "Double R Banden Service",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via Facebook",
          diensten: [
            "Banden opzetten",
            "Banden repareren",
            "BRAND NEW banden verkoop",
          ],
          merken: ["HAIDA", "COMFORSER", "GINELL"],
          specialiteiten: "Importeur van HAIDA, COMFORSER, GINELL",
          beschrijving: "Banden service met eigen import merken",
        },
        {
          naam: "TikuTire N.V.",
          adres: "Leiding 9A #111",
          telefoon: "Beschikbaar via website",
          website: "tikutire.com",
          diensten: [
            "Groot- en kleinhandel banden",
            "Gebruikte banden",
            "Nieuwe banden",
            "Banden reparatie",
          ],
          specialiteiten:
            "Wholesale en retail, complete containers beschikbaar",
          beschrijving: "Surinaamse groot- en kleinhandel in auto banden",
        },
        {
          naam: "N.V. Maximum",
          adres: "Waaldijkstraat #70-#72",
          telefoon: "+597 420227 / +597 474900",
          openingstijden: "Ma-Vr: 7:00-16:30, Za: 8:00-13:00",
          producten: [
            "Nieuwe banden voor personenwagen/terreinwagen/bus/truck",
            "Filters",
            "Smeermiddelen",
            "Onderdelen",
            "Batterijen",
          ],
          diensten: [
            "Onderstel reparatie/service",
            "Uitlijnen",
            "Rotors afdraaien",
            "Balanceren",
            "Remmen vervangen",
          ],
          beschrijving: "Complete banden service met onderstel reparaties",
        },
        {
          naam: "Wim's Banden Service",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via business directory",
          merken: ["Dunlop", "Goodyear", "Bridgestone", "Michelin", "Pirelli"],
          beschrijving: "Banden service met grote selectie van bekende merken",
        },
        {
          naam: "Boss Banden Service",
          adres: "Petrus Donders St 19",
          telefoon: "Beschikbaar via Google Maps",
          type: "Tire shop",
          beschrijving: "Bandenzaak in centrum Paramaribo",
        },
        {
          naam: "FLORA Bandenservice",
          adres: "Licaniastraat (Flora)",
          telefoon: "Beschikbaar via Facebook",
          beschrijving: "Lokale banden service in Flora gebied",
        },
        {
          naam: "Biga Banden Service",
          adres: "Plutostraat 168-170",
          diensten: [
            "Nieuwe en tweedehands banden",
            "Velg rechten en lassen",
            "Auto service",
            "Banden reparatie",
          ],
          beschrijving: "Complete banden service met velg reparaties",
        },
      ],
      autowasserettes: [
        {
          naam: "Bubbles PitStop and Car Wash",
          adres: "Sir Winston Churchillweg 46",
          telefoon: "+597 894-9867",
          email: "Bubblescarwashsu@gmail.com",
          instagram: "bubblescarwashsu",
          diensten: [
            "Express Valet Services (vanaf SRD300)",
            "Premium washes (vanaf SRD400)",
            "American Detail Services (vanaf SRD3000)",
          ],
          specialiteiten:
            "Detailed car wash - geen simpele was maar grondige reiniging",
          beschrijving:
            "Professionele car wash met verschillende service niveaus",
        },
        {
          naam: "TopNotch Carwash & Detailing Services",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via website",
          diensten: [
            "Basic exterior wash",
            "Basic interior vacuuming",
            "Tire shine",
            "Dashboard & ramen reiniging",
          ],
          beschrijving: "Nauwkeurige handwas en interieur reiniging diensten",
        },
        {
          naam: "Autoplaza Carwash",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via Facebook",
          beschrijving: "Car wash service in Paramaribo",
        },
        {
          naam: "Buju's Carwash",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via Facebook",
          beschrijving:
            "Aanbevolen plek voor auto reiniging - vriendelijk en betrouwbaar",
        },
        {
          naam: "Easy-fix Carwash & Detail",
          adres: "Ramalaan #2",
          telefoon: "+597 8908281",
          beschrijving: "Car wash en detailing service",
        },
        {
          naam: "GYR Carwash & More",
          adres: "Hoenderparkweg",
          telefoon: "+597 852-9337",
          beschrijving: "Car wash service met extra diensten",
        },
        {
          naam: "X-Clusive Carwash & Banden Service",
          adres: "Frederik Derbystraat 203",
          telefoon: "+597 7166018",
          website: "xclusivecarwash.webs.com",
          diensten: ["Car wash", "Banden service"],
          beschrijving: "Combinatie car wash en banden service",
        },
        {
          naam: "PUK'S Carwash & Banden Service",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via Facebook",
          diensten: ["Car wash", "Banden service"],
          beschrijving: "Car wash en banden service combinatie",
        },
        {
          naam: "Bubble Cleaning",
          adres: "Tillystraat 69",
          telefoon: "+597 858-8933",
          beschrijving: "Car cleaning service",
        },
        {
          naam: "Romeo's Carwash & More",
          adres: "Florastraat",
          telefoon: "+597 8802071",
          beschrijving: "Car wash met extra diensten",
        },
      ],
      autodealers: [
        {
          naam: "Carmart Suriname",
          adres: "Paramaribo",
          telefoon: "+597 8834344",
          whatsapp: "+1 631-6048558",
          website: "carmartsuriname.com",
          voertuigen: [
            "Toyota RAV4",
            "Honda Vezel",
            "Nissan X-Trail",
            "Nissan Note",
            "Toyota Sienta",
            "Toyota Auris",
          ],
          specialiteiten: "Nieuwe en gebruikte auto's",
          beschrijving: "For the best Price, Quality and Service!",
        },
        {
          naam: "Kersten Motors",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via website",
          website: "kerstenmotors.sr",
          merken: ["Toyota", "Mitsubishi", "Hino"],
          diensten: [
            "Nieuwe auto verkoop",
            "Gebruikte auto verkoop",
            "Service en onderhoud",
          ],
          geschiedenis: "255 jaar ervaring (sinds 1768)",
          beschrijving:
            "Gevestigde dealer met officiële Toyota, Mitsubishi en Hino vertegenwoordiging",
        },
        {
          naam: "Fernandes Autohandel",
          adres: "Keizerstraat 105-117 & Jaggernath Lachmonstraat 126",
          telefoon: "+597 475046",
          whatsapp: "+597 8919554 (Sales & Parts)",
          merken: [
            "Honda",
            "Isuzu",
            "Subaru",
            "Volkswagen Commercial Vehicles",
          ],
          diensten: [
            "Nieuwe auto verkoop",
            "Gebruikte auto verkoop",
            "Service en reparatie",
            "Onderdelen verkoop",
          ],
          openingstijden: "Ma-Vr: 8:00-16:30, Za: 9:00-13:00",
          beschrijving: "Officiële dealer voor Honda en andere merken",
        },
        {
          naam: "Pristine Cars",
          adres: "Van Het Hogerhuysstraat 23",
          telefoon: "Beschikbaar via website",
          website: "pristinecar.sr",
          merk: "Hyundai",
          modellen: [
            "Hyundai Tucson",
            "Hyundai Santa Fe",
            "Hyundai Elantra",
            "Hyundai Creta",
            "Hyundai Venue",
          ],
          diensten: [
            "Nieuwe Hyundai verkoop",
            "Service en reparatie",
            "Onderdelen verkoop",
          ],
          specialiteiten: "Officiële Hyundai vertegenwoordiger",
          beschrijving:
            "Officiële representative van Hyundai met showroom en service",
        },
        {
          naam: "Yokohama Trading N.V.",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via website",
          website: "yokohama.sr",
          specialiteiten: "Gebruikte auto's",
          beschrijving: "Get the best deals on used cars in Suriname",
        },
        {
          naam: "N.V. Super Merchandise Motors",
          adres: "Jaggernath lachmonstraat 60",
          telefoon: "+597 8913626 / +597 532415",
          email: "merchandise_motors@hotmail.com",
          specialiteiten: "Leading Used Car Dealer sinds 2006",
          diensten: ["Gebruikte auto verkoop", "Financiering opties"],
          beschrijving:
            "Gevestigde gebruikte auto dealer met financieringsmogelijkheden",
        },
        {
          naam: "Carmax Suriname",
          adres:
            "Sir Winston Churchillweg, Toekoenariweg 1-3 & 32-54, Dijkveld",
          telefoon: "Beschikbaar via website",
          specialiteiten: "Nieuwe en gebruikte auto's",
          beschrijving: "Used and New Cars Dealer met focus op Japanse import",
        },
        {
          naam: "Suriname Autos",
          adres: "Paramaribo",
          telefoon: "+597 8834344",
          whatsapp: "+1 631-6048558",
          website: "suriautos.com",
          voertuigen: ["Audi Q3", "Volvo XC60"],
          specialiteiten: "Certified used cars",
          beschrijving: "Auto platform voor verkoop en zoeken van auto's",
        },
      ],
      auto_elektronica_audio: [
        {
          naam: "X-Turbo Auto Accessories & Repair",
          adres: "Herman D. Benjaminstraat 67",
          telefoon: "Beschikbaar via Facebook",
          producten: [
            "Car audio systemen",
            "Auto alarm systemen",
            "Car electronics",
          ],
          diensten: ["Installatie", "Reparatie"],
          beschrijving: "Specialist in car audio en alarm systemen",
        },
        {
          naam: "Auto Style N.V.",
          adres: "Verlengde Gemenelandsweg 117",
          telefoon: "+597 497-689",
          producten: ["Alarm systemen", "Sound installatie systemen"],
          diensten: ["Alarm & Sound Installatie"],
          beschrijving: "Installatie van alarm en sound systemen",
        },
        {
          naam: "Kirpalani's N.V. - Audio Devices",
          adres: "Multiple locations",
          telefoon: "Beschikbaar via website",
          producten: ["Car audio systemen", "Speakers", "Audio accessories"],
          merken: ["Samsung", "JBL", "LG", "Pioneer"],
          beschrijving: "Audio apparatuur van bekende merken",
        },
        {
          naam: "Cheungs Center",
          adres: "Paramaribo",
          telefoon: "Beschikbaar via website",
          website: "cheungscenter.com",
          afdelingen: [
            "Cheung's Music (muziekinstrumenten en DJ verlichting)",
            "Cheung's Sound & Vision (TV, Home audio, home theater)",
          ],
          beschrijving: "All in 1 entertainment store met audio en elektronika",
        },
      ],
    },
    totaal_aantal_bedrijven: 67,
    meest_voorkomende_diensten: [
      "Autoreparatie en onderhoud",
      "Auto-onderdelen verkoop",
      "Banden verkoop en service",
      "Car wash diensten",
      "Auto-accessoires verkoop",
      "Nieuwe en gebruikte auto verkoop",
    ],
    populaire_locaties: [
      "Kwattaweg",
      "Keizerstraat",
      "Indira Gandhiweg",
      "Waaldijkstraat",
      "Sir Winston Churchillweg",
      "Verlengde Gemenelandsweg",
    ],
    opmerkingen:
      "Data verzameld via web scraping in augustus 2025. Contactgegevens en openingstijden kunnen wijzigen. Raadpleeg altijd de officiële websites of bel vooraf.",
  },
};
