export const driving_schools = {
  driving_schools: [
    {
      id: 0,
      name: "Rvisionair",
      full_name: "Rvisionair",
      address:
        "Para District · Commewijne District · Paramaribo District · Wanica District",
      phone: "+597 769-7793",
      email: "rvisionairtheorie@gmail.com",
      website: "https://www.facebook.com/profile.php?id=100083565460164",
      facebook: "https://www.facebook.com/profile.php?id=100083565460164",
      instagram: null,
      logo: null,
      established: null,
      specialties: [],
      description:
        "Rvisionair biedt gekwalificeerde online theorie & praktijk lessen aan. Registreer nu voor de online theorie lessen of persoonlijke begeleiding en ervaar 't Gemak!",
      experience_years: null,
      working_hours: null,
      facilities: [],
    },
    {
      id: 1,
      name: "Rijschool Cum Laude",
      full_name: "Rijschool Cum Laude",
      address: "Kasabaholoweg 65, Paramaribo",
      phone: "+597 825-5959",
      email: "rijschool.cumlaude2.0@gmail.com",
      website: "https://rijschoolcumlaude2.com/",
      facebook: "https://www.facebook.com/RijschoolCumLaudeSuriname",
      instagram: null,
      logo: null,
      established: null,
      specialties: [
        "Online theorie rijlessen",
        "Theorie cursus voorbereiding",
        "Online Theorie Spoed Cursus",
        "Pre-recorded lessen",
      ],
      description:
        "Haal Je Surinaams Rijbewijs met Rijschool Cumlaude 2.0! Ben je klaar om de weg op te gaan en je rijvaardigheden naar een hoger niveau te tillen?",
      owner: "Randanzzo (instructor)",
      experience_years: null,
      working_hours: null,
      facilities: [],
      slogan: "100% Tevredenheidsgarantie!",
    },
    {
      id: 2,
      name: "Rijschool Klarex",
      full_name: "Klaar voor het Rij-Examen (KLAREX)",
      address: "Paramaribo, Suriname",
      phone: "+597 893-1328",
      email: null,
      website: "https://rijschoolklarex.com/",
      facebook: "https://www.facebook.com/rijschoolPawiroH/",
      instagram: null,
      logo: null,
      established: null,
      specialties: [
        "Online theorie rijlessen",
        "Maquettelessen",
        "Proefexamens",
        "Audiobegeleiding",
      ],
      description:
        "Rijschool met online theorie-maquettelessen en proefexamens. Pionier in digitaal rijonderwijs in Suriname.",
      owner: "Gerrit Pollack",
      experience_years: "40+ jaren ervaring",
    },
    {
      id: 3,
      name: "Rijschool Pawiro H",
      full_name: "Rijschool Pawiro H.",
      address: "98 Soekaredjoweg, Paramaribo, Wanica, Suriname",
      phone: null,
      email: null,
      website: "https://rijschoolpawiro.com/",
      facebook: null,
      instagram: null,
      logo: null,
      established: null,
      specialties: [
        "Categorie A rijbewijs",
        "Categorie BE rijbewijs",
        "Categorie CE rijbewijs",
        "Categorie DE rijbewijs",
        "Defensief rijstijl",
        "Online lessen",
      ],
      description:
        "Professionele rijschool die verschillende categorieën rijbewijzen aanbiedt. Rijschool voor al uw rijbewijscategorieën, defensief rijstijl & online lessen.",
      facebook_likes: "14,153",
      working_hours: {
        monday: "17:00 - 19:00",
        tuesday: "17:00 - 19:00",
        wednesday: "17:00 - 19:00",
        thursday: "17:00 - 19:00",
        friday: "Closed",
        saturday: "Closed",
        sunday: "Closed",
      },
    },
    {
      id: 4,
      name: "Rijschool Meu",
      full_name: "Rijschool Meu / Meubelman A H",
      address: "Anthuriumstraat #5, Paramaribo, Suriname",
      phone: "+597 499-211",
      email: "rijschoolmeu1@gmail.com",
      website: null,
      facebook: "https://www.facebook.com/p/Rijschool-Meu-100077438035431/",
      instagram: null,
      logo: null,
      established: null,
      specialties: ["Theorie cursus", "Praktijklessen", "Alle categorieën"],
      description:
        "Wij verzorgen theorie- en praktijklessen. Na de theoriecursus heeft u de gelegenheid te oefenen.",
      facebook_likes: "1,599",
      pricing: {
        theory_course: "SRD 2750 (incl. verkeersboek)",
        registration: "SRD 250",
      },
    },
    {
      id: 5,
      name: "Rijschool Kalicharan",
      full_name: "Rijschool Kalicharan",
      address: "190 Kwattaweg, Paramaribo, Suriname",
      phone: null,
      email: null,
      website: null,
      facebook: null,
      instagram: null,
      logo: null,
      established: "1978",
      specialties: ["Beginners lessen", "Ervaren chauffeurs"],
      description:
        "Rijschool met 40+ jaren ervaring in het verzorgen van kwaliteitsrijlessen. Gevestigd in 1978.",
      owner: "Kalicharan Naidu",
      experience_years: "30+ jaren ervaring",
      working_hours: {
        monday: "08:30 - 11:30, 15:00 - 19:30",
        tuesday: "08:30 - 11:30, 15:00 - 19:30",
        wednesday: "08:30 - 11:30, 15:00 - 19:30",
        thursday: "08:30 - 11:30, 15:00 - 19:30",
        friday: "08:30 - 11:30, 15:00 - 19:30",
        saturday: "Closed",
        sunday: "Closed",
      },
      facilities: [
        "Parkeerplaats voor klanten",
        "Airconditioning",
        "Rolstoel toegankelijk",
      ],
    },
    {
      id: 6,
      name: "Rotco's Rijschool",
      full_name: "Rotco's Rijschool",
      address: "Kwattaweg 68 hk Piet Ezechielstraat, Paramaribo, Suriname",
      phone: "+597 470 743",
      fax: "+597 470 743",
      email: "rotco@live.com",
      website: null,
      facebook: null,
      instagram: null,
      logo: null,
      established: "1993",
      specialties: [
        "Beginners lessen",
        "Defensief rijden",
        "Senioren lessen",
        "Speciale behoeften",
      ],
      description:
        "Ervaren rijschool met professioneel rijonderwijs voor studenten door heel het land. 25+ jaren ervaring.",
      experience_years: "25+ jaren ervaring",
      working_hours: {
        monday: "08:30 - 19:00",
        tuesday: "08:30 - 19:00",
        wednesday: "08:30 - 19:00",
        thursday: "08:30 - 19:00",
        friday: "08:30 - 19:00",
        saturday: "08:30 - 12:30",
        sunday: "Closed",
      },
    },
    {
      id: 7,
      name: "Rijschool Sheer Singh",
      full_name: "Rijschool Sheer Singh",
      address: "Coesewijnestraat 97, Paramaribo, Suriname",
      phone: "+597 480 514",
      email: null,
      website: null,
      facebook:
        "https://www.facebook.com/p/Rijschool-Sheer-Singh-100063527734269/",
      instagram: null,
      logo: null,
      established: null,
      specialties: ["Gepersonaliseerde instructie", "Praktische instructie"],
      description:
        "Mission: Empower with driving skills, ensure license success. Unique: Personalized, practical instruction.",
      facebook_likes: "1,005",
      facilities: ["Parkeerplaats voor klanten"],
    },
    {
      id: 8,
      name: "Rijschool Toy",
      full_name: "Rijschool Toy",
      address: "Ming Doelmanstraat 89, Centrum, Paramaribo, Suriname",
      phone: ["+597 454 477", "+597 807 552"],
      fax: "+597 456 723",
      email: null,
      website: null,
      facebook: null,
      instagram: null,
      logo: null,
      established: "1981",
      specialties: [
        "Basis rijonderwijs",
        "Defensief rijden",
        "Examen voorbereiding",
        "Motorrijlessen",
        "Auto verhuur",
        "Voertuig registratie",
      ],
      description:
        "Gerenommeerde rijschool met kwaliteitsrijonderwijs en -training sinds 1981. Bekend om deskundige, vriendelijke instructeurs.",
      experience_years: "40+ jaren ervaring",
    },
    {
      id: 9,
      name: "Rijschool A. Dhoen",
      full_name: "Rijschool A. Dhoen",
      address: "121 Leysweg, Paramaribo, Suriname",
      phone: null,
      email: null,
      website: null,
      facebook: null,
      instagram: null,
      logo: null,
      established: null,
      specialties: [],
      description: "Rijschool gevestigd in het centrum van Paramaribo.",
    },
    {
      id: 10,
      name: "Rijschool GYR",
      full_name: "Rijschool GYR",
      address:
        "Hoenderparkweg 60A (zijstraat Nw. Charlesburgweg), Paramaribo, Suriname",
      phone: "+597 851-9384",
      email: "Rijschoolgyr21@gmail.com",
      website: "https://rijschoolgyrnanco.business.site/",
      facebook: "https://www.facebook.com/p/Rijschool-GYR-100063609066888/",
      instagram: null,
      logo: null,
      established: null,
      specialties: ["Expert lessen", "Spoed cursussen"],
      description:
        "Steering you to success with expert lessons and a passion for driving excellence! Sign up today!",
      facebook_likes: "2,106",
      working_hours: {
        monday: "Always open",
        tuesday: "Always open",
        wednesday: "Always open",
        thursday: "Always open",
        friday: "Always open",
        saturday: "Always open",
        sunday: "Always open",
      },
      slogan:
        "Steering you to success with expert lessons and a passion for driving excellence!",
    },
    {
      id: 11,
      name: "Rijschool Isaya",
      full_name: "Rijschool Isaya",
      address: "Bibi Chiragaliweg #30, Paramaribo, Suriname",
      phone: "+597 874-4504",
      email: null,
      website: null,
      facebook: "https://www.facebook.com/isayarijschool/",
      instagram: null,
      logo: null,
      established: null,
      specialties: ["Kwaliteit", "Plezier", "Flexibiliteit"],
      description: "Wij garanderen kwaliteit, plezier en flexibiliteit!",
      facebook_likes: "317",
    },
    {
      id: 12,
      name: "Rijschool S. Debi Tewari",
      full_name: "Rijschool S. Debi Tewari",
      address: "Paramaribo, Suriname",
      phone: ["+597 816-9112", "+597 862-6377"],
      email: "santoesjapinas1503@gmail.com",
      website: null,
      facebook:
        "https://www.facebook.com/people/Rijschool-S-Debi-Tewari/100088068170181/",
      instagram: null,
      logo: null,
      established: null,
      specialties: ["Online rijlessen", "Theorie vanuit huis"],
      description:
        "Welkom bij Rijschool S.Debi Tewari! Wij bieden hoogwaardige online rijlessen in Suriname. Theorie rijlessen vanuit de comfort van uw huis.",
      facebook_likes: "77",
      slogan:
        "Wil je vanuit de comfort van uw huis of waar dan ook uw theorie rijlessen volgen? Dat kan!",
    },
    {
      id: 13,
      name: "Rijschool Lelydorp",
      full_name: "Rijschool (Lelydorp)",
      address: "Lelydorp, Suriname",
      phone: null,
      email: null,
      website: null,
      facebook: null,
      instagram: null,
      logo: null,
      established: "2001",
      specialties: ["Defensief rijden", "Eco-rijden", "Basis rijlessen"],
      description:
        "Rijschool die kwaliteitsrijonderwijs biedt aan alle klanten. Gespecialiseerd in defensief rijden, eco-rijden en basis rijlessen.",
      experience_years: "20+ jaren ervaring (sinds 2001)",
    },
    {
      id: 14,
      name: "Climax Rijschool",
      full_name: "Climax Rijschool",
      address: "Orleanestraat #14, Paramaribo, Suriname",
      phone: "+597 880-5118",
      email: null,
      website: null,
      facebook: null,
      instagram: null,
      logo: null,
      established: null,
      specialties: ["Theoretische rijlessen"],
      description:
        "Rijschool gespecialiseerd in theoretische rijlessen. Actief op zoek naar docenten voor het verzorgen van theoretische rijlessen.",
    },
    {
      id: 15,
      name: "Rijschool Albina",
      full_name: "Rijschool Albina",
      address: "Gouverneurstraat, Albina, Suriname",
      phone: null,
      email: null,
      website: null,
      facebook: null,
      instagram: null,
      logo: null,
      established: null,
      specialties: [],
      description: "Rijschool gevestigd in Albina, Marowijne district.",
      working_hours: {
        monday: "15:00 - 17:00",
        tuesday: "15:00 - 17:00",
        wednesday: "15:00 - 17:00",
        thursday: "Closed",
        friday: "Closed",
        saturday: "Closed",
        sunday: "Closed",
      },
      note: "Extra lesdagen ook mogelijk",
    },
    {
      id: 16,
      name: "Rij School Texas",
      full_name: "Rij School Texas",
      address: "Molenpad 10 Centrum, Paramaribo, Suriname",
      phone: "+597 403-854",
      email: null,
      website: null,
      facebook: null,
      instagram: null,
      logo: null,
      established: null,
      specialties: [],
      description: "Rijschool gevestigd in het centrum van Paramaribo.",
    },
    {
      id: 17,
      name: "Rij School Soleram",
      full_name: "Rij School Soleram",
      address: "Tourtonnelaan Blauwgrond, Paramaribo, Suriname",
      phone: null,
      email: null,
      website: null,
      facebook: null,
      instagram: null,
      logo: null,
      established: null,
      specialties: [],
      description: "Rijschool gevestigd in Blauwgrond, Paramaribo.",
    },
  ],
  metadata: {
    total_schools: 17,
    city: "Paramaribo",
    country: "Suriname",
    districts_covered: [
      "Paramaribo",
      "Wanica",
      "Lelydorp",
      "Albina (Marowijne)",
    ],
    last_updated: "2025-08-17",
    data_sources: [
      "Facebook",
      "Business directories",
      "Waze",
      "Company websites",
      "VyMaps",
      "UnitedNews",
    ],
    note: "Contact information collected from publicly available sources. Some schools may have additional contact methods not listed here. Includes schools from greater Paramaribo area including Lelydorp, Wanica and Albina.",
    additional_contact_found: {
      rotco_email: "rotco@live.com",
      kalicharan_phone_alt: "+597 893-1328",
      klarex_alt_address: "Bibi Chiragaliweg #30, Paramaribo",
      klarex_phone: "+597 874-4504",
    },
  },
};
