  

export const trafficSignsData = [
  {
    id: 1,
    name: "Model 1",
    image: "/borden/model_1.svg",
    description: "Omhoog gestrekte arm met de handpalm naar voren gekeerd.",
    rule: "Stopteken voor het verkeer dat de verkeersagent van voren nadert.",
  },
  {
    id: 2,
    name: "Model 2",
    image: "/borden/model_2.svg",
    description:
      "Eén arm zijwaarts gestrekt naar de kant van de rijbaan waarlangs het betrokken verkeer nadert, met de handpalm naar voren gericht.",
    rule: "Stop voor verkeer van achteren. Mag samen met model 1 gebruikt worden.",
  },
  {
    id: 3,
    name: "Model 3 en 4",
    image: "/borden/model_3_4.svg",
    description:
      "Eén arm zijwaarts met de handpalm naar boven gericht wenkend naar de schouder.",
    rule: "Oprijden vanaf wenkende arm. Van voren/achteren: stop.",
  },
  {
    id: 4,
    name: "Model 5 en 6",
    image: "/borden/model_5_6.svg",
    description:
      "Eén arm zijwaarts met de handpalm naar beneden gericht en de ellebogen gebogen wenkend langs het lichaam.",
    rule: "Langzamer rijden vanaf wenkende arm.",
  },
  {
    id: 5,
    name: "Model 7 en 8",
    image: "/borden/model_7_8.svg",
    description:
      "Eén arm zijwaarts gestrekt met de handpalm naar beneden gericht, op en neer bewogend.",
    rule: "Sneller rijden vanaf bewegende arm.",
  },
  {
    id: 6,
    name: "Model 9",
    image: "/borden/model_9.svg",
    description: "",
    rule: "Stop als bord loodrecht wordt getoond.",
  },
  {
    id: 7,
    name: "Model 10",
    image: "/borden/model_10.svg",
    description: "",
    rule: "Doorrijden als bord loodrecht wordt getoond.",
  },
  {
    id: 8,
    name: "Model 11",
    image: "/borden/model_11.svg",
    description: "",
    rule: "Nadering voorrangsweg kruising of splitsing",
  },
  {
    id: 9,
    name: "Model 12d",
    image: "/borden/model_12d.svg",
    description: "",
    rule: "Stop en verleen voorrang aan het verkeer op de andere weg",
  },
  {
    id: 10,
    name: "Model 12",
    image: "/borden/model_12.svg",
    description: "",
    rule: "Stop en verleen voorrang aan het verkeer op de andere weg",
  },
  {
    id: 11,
    name: "Model 12a",
    image: "/borden/model_12a.svg",
    description: "",
    rule: "Voorrang op deze weg bij kruising/splitsing.",
  },
  {
    id: 12,
    name: "Model 13",
    image: "/borden/model_13.svg",
    description: "",
    rule: "Verboden voor alle verkeer in beide richtingen.",
  },
  {
    id: 13,
    name: "Model 14",
    image: "/borden/model_14.svg",
    description: "",
    rule: "Verboden voor alle verkeer in één richting.",
  },
  {
    id: 14,
    name: "Model 15",
    image: "/borden/model_15.svg",
    description: "",
    rule: "Verbod voor alle motorrijtuigen op meer dan 2 wielen",
  },
  {
    id: 15,
    name: "Model 16",
    image: "/borden/model_16.svg",
    description: "",
    rule: "Verbod voor motorrijtuigen op twee wielen",
  },
  {
    id: 16,
    name: "Model 17",
    image: "/borden/model_17.svg",
    description: "",
    rule: "Verkeer gesloten voor alle motorrijtuigen",
  },
  {
    id: 17,
    name: "Model 18",
    image: "/borden/model_18.svg",
    description: "",
    rule: "Verboden voor karren met trekdieren en handkarren.",
  },
  {
    id: 18,
    name: "Model 19",
    image: "/borden/model_19.svg",
    description: "",
    rule: "Verboden voor rijwielen",
  },
  {
    id: 19,
    name: "Model 20",
    image: "/borden/model_20.svg",
    description: "",
    rule: "Gesloten voor rij- en voertuigen met grotere breedte dan aangegeven",
  },
  {
    id: 20,
    name: "Model 21",
    image: "/borden/model_21.svg",
    description: "",
    rule: "Gesloten voor rij- en voertuigen met grotere hoogte dan aangegeven",
  },
  {
    id: 21,
    name: "Model 22",
    image: "/borden/model_22.svg",
    description: "",
    rule: "Gesloten voor rij- of voertuigen met groter gewicht dan aangegeven",
  },
  {
    id: 22,
    name: "Model 22a",
    image: "/borden/model_22a.svg",
    description: "",
    rule: "Verboden bij overschrijding asdruk.",
  },
  {
    id: 23,
    name: "Model 23",
    image: "/borden/model_23.svg",
    description: "",
    rule: "Verboden verkeer behalve pijlrichting.",
  },
  {
    id: 24,
    name: "Model 23a",
    image: "/borden/model_23a.svg",
    description: "",
    rule: "Verboden verkeer (behalve voetgangers) aan andere kant dan pijl.",
  },
  {
    id: 25,
    name: "Model 23h",
    image: "/borden/model_23h.svg",
    description: "",
    rule: "Gebod tot het volgen van één van de rijrichtingen die het bord zijn aangegeven.",
  },
  {
    id: 26,
    name: "Model 23j",
    image: "/borden/model_23j.svg",
    description: "",
    rule: "Gebod tot het volgen van één van de rijrichtingen die het bord zijn aangegeven.",
  },
  {
    id: 27,
    name: "Model 23k",
    image: "/borden/model_23k.svg",
    description: "",
    rule: "Bestuurders mogen dit bord aan beide zijden voorbijrijden",
  },
  {
    id: 28,
    name: "Model 24",
    image: "/borden/model_24.svg",
    description: "",
    rule: "Eenrichtingsweg",
  },
  {
    id: 29,
    name: "Model 25",
    image: "/borden/model_25.svg",
    description: "",
    rule: "Linksaf verboden voor alle verkeer.",
  },
  {
    id: 30,
    name: "Model 26",
    image: "/borden/model_26.svg",
    description: "",
    rule: "Rechtsaf verboden voor alle verkeer.",
  },
  {
    id: 31,
    name: "Model 26a",
    image: "/borden/model_26a.svg",
    description: "",
    rule: "Verbod om te keren",
  },
  {
    id: 32,
    name: "Model 27",
    image: "/borden/model_27.svg",
    description: "",
    rule: "Inhaalverbod voor motorrijtuigen >2 wielen.",
  },
  {
    id: 33,
    name: "Model 27a",
    image: "/borden/model_27a.svg",
    description: "",
    rule: "Einde inhaalverbod motorrijtuigen >2 wielen.",
  },
  {
    id: 34,
    name: "Model 28",
    image: "/borden/model_28.svg",
    description: "",
    rule: "Tegenligger heeft voorrang. Rode pijl moet wachten.",
  },
  {
    id: 35,
    name: "Model 29",
    image: "/borden/model_29.svg",
    description: "",
    rule: "Verkeer in richting witte pijl heeft voorrang",
  },
  {
    id: 36,
    name: "Model 30",
    image: "/borden/model_30.svg",
    description: "",
    rule: "Stopverbod beide zijden. Ook geen passagiers laten in-/uitstappen.",
  },
  {
    id: 37,
    name: "Model 31",
    image: "/borden/model_31.svg",
    description: "",
    rule: "Stopverbod links. Alleen rechts stoppen toegestaan.",
  },
  {
    id: 38,
    name: "Model 32",
    image: "/borden/model_32.svg",
    description: "",
    rule: "Stopverbod rechts. Alleen links stoppen toegestaan.",
  },
  {
    id: 39,
    name: "Model 32a",
    image: "/borden/model_32a.svg",
    description: "",
    rule: "Verbod stil te staan.",
  },
  {
    id: 40,
    name: "Model 33",
    image: "/borden/model_33.svg",
    description: "",
    rule: "Wachtverbod voor beide zijden van de weg",
  },
  {
    id: 41,
    name: "Model 34",
    image: "/borden/model_34.svg",
    description: "",
    rule: "Wachtverbod links. Alleen rechts wachten toegestaan.",
  },
  {
    id: 42,
    name: "Model 35",
    image: "/borden/model_35.svg",
    description: "",
    rule: "Wachtverbod rechts. Alleen links wachten toegestaan.",
  },
  {
    id: 43,
    name: "Model 42",
    image: "/borden/model_42.svg",
    description: "",
    rule: "Verplicht rijwielpad. Tweewielige bromfietsen/fietsen hier. >2 wielen op rijbaan.",
  },
  {
    id: 44,
    name: "Model 43",
    image: "/borden/model_43.svg",
    description: "",
    rule: "Parkeerplaats",
  },
  {
    id: 45,
    name: "Model 43a",
    image: "/borden/model_43a.svg",
    description: "",
    rule: "Verboden hier te staan of te parkeren.",
  },
  {
    id: 46,
    name: "Model 44",
    image: "/borden/model_44.svg",
    description: "",
    rule: "Te volgen richting bij wegafsluiting.",
  },
  {
    id: 47,
    name: "Model 44a",
    image: "/borden/model_44a.svg",
    description: "",
    rule: "Nadering voorsorteervakken",
  },
  {
    id: 48,
    name: "Model 45",
    image: "/borden/model_45.svg",
    description: "",
    rule: "Voorrangsweg",
  },
  {
    id: 49,
    name: "Model 46",
    image: "/borden/model_46.svg",
    description: "",
    rule: "Einde voorrangsweg",
  },
  {
    id: 50,
    name: "Model 47",
    image: "/borden/model_47.svg",
    description: "",
    rule: "Maximumsnelheid zoals aangegeven.",
  },
  {
    id: 51,
    name: "Model 48",
    image: "/borden/model_48.svg",
    description: "",
    rule: "Einde snelheidsbeperking",
  },
  {
    id: 52,
    name: "Model 48a",
    image: "/borden/model_48a.svg",
    description: "",
    rule: "Verplicht maximumsnelheidsbord voor tractoren op openbare weg.",
  },
  {
    id: 53,
    name: "Model 48b",
    image: "/borden/model_48b.svg",
    description: "",
    rule: "Gevaar lengte aanhangwagen of oplegger",
  },
  {
    id: 54,
    name: "Model 49",
    image: "/borden/model_49.svg",
    description: "",
    rule: "Verplicht voetpad",
  },
  {
    id: 55,
    name: "Model 50",
    image: "/borden/model_50.svg",
    description: "",
    rule: "Algemeen gevaarteken",
  },
  {
    id: 56,
    name: "Model 51",
    image: "/borden/model_51.svg",
    description: "",
    rule: "Gevaarlijke bocht - vaart verminderen.",
  },
  {
    id: 57,
    name: "Model 51a",
    image: "/borden/model_51a.svg",
    description: "",
    rule: "S bocht of bochten eerst naar links",
  },
  {
    id: 58,
    name: "Model 51b",
    image: "/borden/model_51b.svg",
    description: "",
    rule: "S-bocht of bochten eerst naar rechts",
  },
  {
    id: 59,
    name: "Model 52",
    image: "/borden/model_52.svg",
    description: "",
    rule: "Gevaarlijk kruispunt",
  },
  {
    id: 60,
    name: "Model 52a",
    image: "/borden/model_52a.svg",
    description: "",
    rule: "Uitholling of slecht wegdek.",
  },
  {
    id: 61,
    name: "Model 52b",
    image: "/borden/model_52b.svg",
    description: "",
    rule: "Werk in uitvoering",
  },
  {
    id: 62,
    name: "Model 52c",
    image: "/borden/model_52c.svg",
    description: "",
    rule: "Stijle of gevaarlijk helling",
  },
  {
    id: 63,
    name: "Model 53",
    image: "/borden/model_53.svg",
    description: "",
    rule: "Wegversmalling",
  },
  {
    id: 64,
    name: "Model 53a",
    image: "/borden/model_53a.svg",
    description: "",
    rule: "Wegversmalling rechts.",
  },
  {
    id: 65,
    name: "Model 53b",
    image: "/borden/model_53b.svg",
    description: "",
    rule: "Wegversmalling links.",
  },
  {
    id: 66,
    name: "Model 53c",
    image: "/borden/model_53c.svg",
    description: "",
    rule: "Slipgevaar",
  },
  {
    id: 67,
    name: "Model 53d",
    image: "/borden/model_53d.svg",
    description: "",
    rule: "Doodlopende weg",
  },
  {
    id: 68,
    name: "Model 53e",
    image: "/borden/model_53e.svg",
    description: "",
    rule: "Vooraanduiding doodlopende weg",
  },
  {
    id: 69,
    name: "Model 53f",
    image: "/borden/model_53f.svg",
    description: "",
    rule: "Vooraanduiding doodlopende weg",
  },
  {
    id: 70,
    name: "Model 53g",
    image: "/borden/model_53g.svg",
    description: "",
    rule: "Vooraanduiding doodlopende weg",
  },
  {
    id: 71,
    name: "Model 54",
    image: "/borden/model_54.svg",
    description: "",
    rule: "Oversteekplaats voor voetgangers",
  },
  {
    id: 72,
    name: "Model 55",
    image: "/borden/model_55.svg",
    description: "",
    rule: "Kinderen, school, speelplaats",
  },
  {
    id: 73,
    name: "Model 56",
    image: "/borden/model_56.svg",
    description: "",
    rule: "Onbewaakte spoorwegovergang",
  },
  {
    id: 74,
    name: "Model 56a",
    image: "/borden/model_56a.svg",
    description: "",
    rule: "Kade of riviertoever",
  },
  {
    id: 75,
    name: "Model 56b",
    image: "/borden/model_56b.svg",
    description: "",
    rule: "Fietsers/bromfietsers steken over.",
  },
  {
    id: 76,
    name: "Model 56c",
    image: "/borden/model_56c.svg",
    description: "",
    rule: "Tegenliggers",
  },
  {
    id: 77,
    name: "Model 56d",
    image: "/borden/model_56d.svg",
    description: "",
    rule: "Laagvliegende vliegtuigen",
  },
  {
    id: 78,
    name: "Model 56e",
    image: "/borden/model_56e.svg",
    description: "",
    rule: "Nadering verkeerslichten",
  },
  {
    id: 79,
    name: "Model 57",
    image: "/borden/model_57.svg",
    description: "",
    rule: "Ziekenhuis - geen onnodig lawaai.",
  },
  {
    id: 80,
    name: "Model 57a",
    image: "/borden/model_57a.svg",
    description: "",
    rule: "Bushalte",
  },
  {
    id: 81,
    name: "Model 58",
    image: "/borden/model_58.svg",
    description: "",
    rule: "Plaatsnaam, begin bebouwde kom",
  },
  {
    id: 82,
    name: "Model 59",
    image: "/borden/model_59.svg",
    description: "",
    rule: "Plaatsnaam, einde bebouwde kom",
  },
  {
    id: 83,
    name: "Model 60",
    image: "/borden/model_60.svg",
    description: "",
    rule: "Onderborden geven interpretatie of beperkingen van hoofdbord aan.",
  },
  {
    id: 84,
    name: "Model 61",
    image: "/borden/model_61.svg",
    description: "",
    rule: "Autoweg",
  },
  {
    id: 85,
    name: "Model 62",
    image: "/borden/model_62.svg",
    description: "",
    rule: "Einde autoweg",
  },
  {
    id: 86,
    name: "Model 63",
    image: "/borden/model_63.svg",
    description: "",
    rule: "Telefoon",
  },
  {
    id: 87,
    name: "Model 64",
    image: "/borden/model_64.svg",
    description: "",
    rule: "Benzinepomp op aangegeven afstand.",
  },
  {
    id: 88,
    name: "Model 65",
    image: "/borden/einde_verboden.svg",
    description: null,
    rule: "Einde alle verboden.",
  },
  {
    id: 89,
    name: "Bocht naar links",
    image: "/borden/bocht_links.svg",
    description: null,
    rule: "Bocht naar links.",
  },
  {
    id: 90,
    name: "Bocht naar rechts",
    image: "/borden/bocht_rechts.svg",
    description: null,
    rule: "Bocht naar rechts.",
  },
  {
    id: 91,
    name: "Aanduiding voorrang",
    image: "/borden/voorrang_van_links.svg",
    description: null,
    rule: "Voorrang aan verkeer van rechts en links.",
  },
  {
    id: 92,
    name: "Aanduiding voorrang",
    image: "/borden/voorrang_van_rechts.svg",
    description: null,
    rule: "Voorrang aan verkeer van rechts en links.",
  },
  {
    id: 93,
    name: "DOUANE",
    image: "/borden/douane.svg",
    description: null,
    rule: "Verplicht stoppen bij douane.",
  },
  {
    id: 94,
    name: "Voorrangsweg aanduiding",
    image: "/borden/verloop_voorrangsweg_a.svg",
    description: null,
    rule: "Dikke lijn = voorrangsweg, dunne lijn = zijweg.",
  },
  {
    id: 95,
    name: "Voorrangsweg aanduiding",
    image: "/borden/verloop_voorrangsweg_b.svg",
    description: null,
    rule: "Dikke lijn = voorrangsweg, dunne lijn = zijweg.",
  },
  {
    id: 96,
    name: "Voorrangsweg aanduiding",
    image: "/borden/verloop_voorrangsweg_c.svg",
    description: null,
    rule: "Dikke lijn = voorrangsweg, dunne lijn = zijweg.",
  },
  {
    id: 97,
    name: "Bebakening spoorwegovergang",
    image: "/borden/bebakening_spoorweg.svg",
    description: null,
    rule: "Bebakening spoor-/tramwegovergang.",
  },
  {
    id: 98,
    name: "Andreaskruis enkel spoor",
    image: "/borden/spoorweg_overgang_a.svg",
    description: null,
    rule: "Onbewaakte spoorwegovergang - enkel spoor.",
  },
  {
    id: 99,
    name: "Andreaskruis meerdere sporen",
    image: "/borden/spoorweg_overgang_b.svg",
    description: null,
    rule: "Onbewaakte spoorwegovergang - meerdare sporen.",
  },
  {
    id: 100,
    name: "Model 23i",
    image: "/borden/model_23i.svg",
    description: "",
    rule: "Gebod tot het volgen van één van de rijrichtingen die het bord zijn aangegeven.",
  },
  {
    id: 101,
    name: "Beweegbare brug",
    image: "/borden/beweegbare_brug.svg",
    description: null,
    rule: "Beweegbare brug.",
  },
  {
    id: 102,
    name: "Blindestok",
    image: "/borden/blindestok.svg",
    description: null,
    rule: "Blindestok.",
  },
  {
    id: 103,
    name: "Drempel",
    image: "/borden/drempel.svg",
    description: null,
    rule: "Let op drempel. Hier ligt de drempel.",
  },
  {
    id: 104,
    name: "Einde rijstrook",
    image: "/borden/einde_rijstrook.svg",
    description: null,
    rule: "Einde rijstrook.",
  },
  {
    id: 105,
    name: "Nadering verkeersdrempel",
    image: "/borden/nadering_drempel.svg",
    description: null,
    rule: "Nadering verkeersdrempel. Langzaam rijden.",
  },
  {
    id: 106,
    name: "Nadering verkeersplein",
    image: "/borden/nadering_verkeersplein.svg",
    description: null,
    rule: "Nadering verkeersplein of rotonde.",
  },
  {
    id: 107,
    name: "Opengebroken weggedeelte",
    image: "/borden/opengebroken_weggedeelte.svg",
    description: null,
    rule: "Opengebroken weggedeelte, wegvernauwing, walkant en dergelijke.",
  },
  {
    id: 108,
    name: "Overstekende runderen",
    image: "/borden/overstekende_runderen.svg",
    description: null,
    rule: "Pas op voor overstekende runderen.",
  },
  {
    id: 109,
    name: "Plaatsnaam einde",
    image: "/borden/plaatsnaam_einde.svg",
    description: null,
    rule: "Plaatsnaam einde bebouwde kom.",
  },
  {
    id: 110,
    name: "Rotonde",
    image: "/borden/rotonde.svg",
    description: null,
    rule: "Verkeersplein.",
  },
  {
    id: 111,
    name: "Verboden zwaarmaterieel",
    image: "/borden/verboden_zwaarmaterieel.svg",
    description: null,
    rule: "Verboden voor vrachtwagens.",
  },
  {
    id: 112,
    name: "Verkeersbrigadier",
    image: "/borden/verkeers_brigadier.svg",
    description: null,
    rule: "Stop. ( dit teken wordt veel gegeven door aangewezen verkeersbrigadiers, andere scholieren en/of leerkrachten).",
  },
  {
    id: 113,
    name: "Verkeersplein",
    image: "/borden/verkeersplein.svg",
    description: null,
    rule: "Verkeersplein, verplichte rijrichting.",
  },
  {
    id: 114,
    name: "Voetgangers verboden",
    image: "/borden/voetgangers_verboden.svg",
    description: null,
    rule: "Verboden voor voetgangers.",
  },
];
